### PR TITLE
new_merkle_tree function

### PR DESCRIPTION
**Pull request by vicentevieytes**
The MerkleNode is a sufficient data structure to represent a full merkle tree.

Implement a function that constructs the root MerkleNode from the &[u8] input data.

### CODE REVIEW

**Comment by vicentevieytes** [comment]
I am thinking maybe i should make this function an impl of MerkleNode, or create a new struct MerkleTree which would wrap the root MerkleNode and implement the methods for constructing and modifying full MerkleTrees.

**Review by MarcosNicolau — COMMENTED** [review]
Logic looks good to me. Here are some comments:
- I would try to split the function into more functions for easier readability and understandability of what the code is doing at each step. 
- Use impls for the creation of the tree `MerkleTree::From(vec)`.
- Use `self` in the `new_leaf` and `combine` so that you can call it directly without the namespace.

Other than that, it looks great! 😃

**Comment by vicentevieytes** [comment]
Great, about each of your comments:

1. I will refactor some of the code into functions for readability and re-request review from you.
2. I was working on implementing the MerkleTree struct and placing the constructors as an impl of that struct on another branch (see https://github.com/vicentevieytes/merkle-tree/pull/2) i will rebase the first commits from that branch into this one and re-request review.


3. At least with the `new_leaf` function i wouldn't pass self, since it's a constructor which takes the data and creates the MerkleNode, it doesn't need another instance of MerkleNode for it to work. For the `combine` constructor it's a design choice, the difference would be constructing the node like this:

```left_node.combine(right_node)```
or like this:
```MerkleNode::combine(left_node, right_node)```

**Comment by MarcosNicolau** [comment]
Perfect. Regarding point 3: now that I think of it, your decisions do actually make more sense than what I proposed 😁.

**Review by MarcosNicolau — COMMENTED** [review]
The code is much cleaner now. What I would change:
- Put the merkle_tree functions(`new_merkle_tree`, `merkle_leaves`, `next_merkle_level`) inside the `impl MerkleTree` so that all the implementations are under the same namespace facilitating the interactions with the lib.
- I would rename the merkle tree functions. For example: 
    - `merkle_leaves`-> `get_leaves`
    - `new_merkle_tree` -> `create_from`. 
   Notice that I removed the `merkle_leaves` prefix coz of 1.

**Review by MarcosNicolau — APPROVED** [review]
LGTM! 👍

**Pull request merged**
